sudo: required
services: 
  - docker

before_install:
  - docker build -t phong/docker-react -f Dockerfile.dev .

script:
  - docker run phong/docker-react yarn run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-401241841858"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  
  